version: '3.2'
services:
  web-app:
    build: .
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
    restart: on-failure
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - postgres-db:/db/data
    environment:
      - POSTGRES_DB=driving_school
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
volumes:
  postgres-db: